### ISSUE TITLE
Missing Phrase

### ISSUE THREAD

**Issue by SushiRoll55** [murphyne/unity-answers-anonymous#1]
It seems that the phrase "min" is also subject to this issue, which I noticed when reading a forum where someone said "unnecessarily resource consu`$$anonymous$$`g." and the script changed it to "unnecessarily resource consuMg."

**Comment by murphyne** [comment]
Thanks for the report! An update with a fix is now available.

**Comment by murphyne** [comment]
Fixed in 4da6e0e66bd2c42282fa1c5e6a2d15e8f3b180d3.
